<a href="https://colab.research.google.com/github/Gonza03s/intro-analisis-de-datos/blob/master/numpy_clase_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atributos de un array y tipos de datos

## Por qué importa conocer los atributos de un array

Cuando trabajamos con datos reales (por ejemplo, un array que armó otra persona, o que
sale de leer un archivo), casi nunca conocemos de entrada su forma exacta ni el tipo de
dato que contiene. Los **atributos** de un `ndarray` son propiedades que NumPy calcula
automáticamente y que nos permiten "inspeccionar" cualquier array sin tener que
adivinar: cuántas dimensiones tiene, qué forma tiene, de qué tipo son sus datos, y
cuánta memoria está usando. Dominar estos atributos es fundamental porque **la mayoría
de los errores que se cometen con NumPy** (sobre todo en operaciones entre arrays, como
vamos a ver más adelante con broadcasting) tienen que ver con no tener del todo claro
la forma o el tipo de dato con el que estamos trabajando en cada paso.

## El concepto de `dtype` (tipo de dato)

Ya lo mencionamos en Clase 1, pero vale la pena remarcarlo bien acá: a diferencia de
una lista de Python (donde cada elemento puede ser de un tipo distinto: un número, un
texto, otra lista...), en un `ndarray` **todos los elementos tienen que ser del mismo
tipo de dato**. Ese tipo se llama `dtype` (*data type*), y NumPy lo elige
automáticamente según los valores que le pasemos (por ejemplo, `int64` para números
enteros, `float64` para decimales), aunque también se lo podemos indicar nosotros de
forma explícita. Esta homogeneidad es justamente lo que le permite a NumPy guardar los
datos en un bloque compacto de memoria y operar sobre ellos a máxima velocidad.


##funciones para ver como esta compuesto un array

Ya usamos varios de estos atributos de pasada en la Clase 1. Ahora los vamos a ver uno por uno, con calma, porque son los que más se usan a diario para "inspeccionar" un array del que no conocemos la forma (por ejemplo, cuando recibimos datos de otra persona o de un archivo).

`ndim` nos dice **cuántas dimensiones** tiene el array (1 para un vector, 2 para una matriz, 3 o más para arrays de mayor dimensión).

In [ ]:
import numpy as np

In [ ]:
# ver cuantas dimensiones tiene un array, en nuestro caso una dimension ya que es un vector
a = np.array([3, 14, 15, 92])
a.ndim

1

`shape` devuelve una **tupla** con el tamaño de cada dimensión. Es probablemente el atributo que más se consulta en la práctica, porque muchos errores al operar con arrays son en realidad errores de "formas incompatibles".

In [ ]:
# shape para ver la "forma" del array, le devuelve en forma de tupla.
# en nuestro caso es una tupla de un unico valor, ya que tiene una sola dimension y la cantidad de elementos.
a.shape

# Ejemplos prácticos:
# 1D (Vector): (5,) -> Un arreglo unidimensional con 5 elementos.
# 2D (Matriz): (3, 4) -> Un arreglo de 3 filas y 4 columnas.
# 3D (Tensor): (2, 3, 4) -> Un arreglo con 2 bloques/matrices, donde cada una tiene 3 filas y 4 columnas.

(4,)

`dtype` nos dice el **tipo de dato** de los elementos que contiene el array. Recordá que todos los elementos de un `ndarray` comparten el mismo `dtype` — esa homogeneidad es justamente lo que permite que NumPy sea tan eficiente.

In [ ]:
# para comprobar el tipo de dato (data type)
a.dtype # En este caso es int64 (64 bits = 8 bytes), puede cambiar segun la maquina donde se este ejecutando.

dtype('int64')

`size` es la cantidad **total** de elementos del array (equivalente a multiplicar todos los valores de `shape` entre sí, o a `len()` cuando el array es de una sola dimensión).

In [ ]:
# nos permite ver el numero de elementos de un array.
a.size # es lo mismo que len(a)

4

### Repaso: arrays desde listas y desde tuplas

Como vimos en el Video 1, `np.array()` acepta tanto listas como tuplas de Python — el resultado es exactamente el mismo `ndarray`, no hay ninguna diferencia funcional.

In [ ]:
# RECORDAR
# también se puede crear un array con tuplas.
# no se diferencia en nada al creado con una lista
a1 = np.array((3, 14, 15, 92))
print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.dtype)
a1

[ 3 14 15 92]
1
(4,)
int64


array([ 3, 14, 15, 92])

### `itemsize` y `nbytes`: el costo en memoria

- `itemsize`: cuántos **bytes** ocupa cada elemento individual (depende pura y exclusivamente del `dtype`).
- `nbytes`: cuántos bytes ocupa el array **completo** en memoria (es simplemente `itemsize * size`).

Esto es súper útil cuando trabajamos con datasets grandes: nos permite calcular, antes de cargar algo pesado, cuánta memoria RAM va a necesitar.

In [ ]:
# comprobaremos el tamaño que tienen
a2 = np.array([1,2,3,4,5])

# tamaño de cada uno de los elementos que componen el array
print(a2.itemsize) # en nuestro caso 8 bytes

# tamaño total en memoria que tiene nuestro array o VECTOR
print(a2.nbytes) # es 40, porque 8 bytes por 5 elementos que tiene nuestro array

8
40


### Arrays de strings (texto)

NumPy también puede guardar cadenas de texto, aunque no es su uso más habitual (para eso solemos preferir Pandas más adelante en el curso). Lo interesante acá es ver el `dtype` que le asigna: algo como `<U5`. Eso significa:
- `<`: el orden de bytes (poco relevante para nosotros ahora).
- `U`: Unicode (texto).
- `5`: la cantidad MÁXIMA de caracteres que puede tener cada elemento — determinada por la cadena más larga que pusimos en el array.

In [ ]:
# tambien podemos incluir cadenas en nuestros arrays.
a3 = np.array(["Hola", "Mundo"])
print(a3.dtype) # vemos el tipo de dato es <U5

# esto significa que esta escrito en la codificacion UTF y
# que el numero maximo de caracteres que admite es 5. Es 5
# porque la cadena mas larga que es "Mundo" tiene 5 caracteres.
# ver como cambia si escribimos una cadena mas larga o mas corta. Por ejemplo "Mundos"

<U5


In [ ]:
print(a3.itemsize) # cada palabra ocupa 20 bytes, porque es 5 x 4 (toma que todas las palabas tienen un tamaño de 5, por "Mundo")
print(a3.nbytes) # y como hay 2 palabras, 20 x 2 = 40

20
40


### ¿Qué pasa si mezclamos tipos de datos?

Como dijimos, un `ndarray` **tiene que ser homogéneo**. Entonces, ¿qué hace NumPy cuando le damos una lista con tipos mezclados? Los convierte automáticamente a un único tipo común, siguiendo una jerarquía de "quién puede representar a quién sin perder información":

- Si mezclamos **enteros y texto** → todo se convierte a **texto** (porque un número siempre se puede representar como texto, pero no al revés).
- Si mezclamos **decimales y texto** → también todo a texto.
- Si mezclamos **enteros, decimales y texto** → todo a texto, y con el tamaño máximo necesario para la cadena más larga.

In [ ]:
# si ponemos diferentes tipos de datos, los va a transformar en uno de ellos
a4 = np.array([14, "Python"]) # en este caso ponemos enteros y caracteres
print(a4)
print(a4.dtype) # nos dice que va a llegar hasta 21 caracteres


a5 = np.array([3.14, "Python"]) # en este caso ponemos flotantes y caracteres
print(a5)
print(a5.dtype) # nos dice que va a llegar hasta 32 caracteres


# si mezclamos estos 3 tipos de datos
# todo se va a transformar a cadena y al maximo tamaño
a6 = np.array([3.14, "Python", 15])
print(a6)
print(a6.dtype)

['14' 'Python']
<U21
['3.14' 'Python']
<U32
['3.14' 'Python' '15']
<U32


### El tipo del objeto vs. el tipo de los datos

Ojo con no confundir dos cosas parecidas pero distintas:
- `type(a)` → el tipo de **objeto de Python**, que siempre va a ser `numpy.ndarray`, sin importar qué datos contenga.
- `a.dtype` → el tipo de **los datos** que contiene ese ndarray (`int64`, `float64`, `<U5`, etc.).

También es útil recordar que un `ndarray` se puede convertir de vuelta a una lista de Python con `list()`, por si en algún momento necesitamos trabajar con las herramientas nativas de Python.

In [ ]:
# el tipo de dato de un array de numpy es numpy.ndarray, obviamente independientemente del tipo de dato que usemos
# ndarray significa n-dimensional array
a7 = np.array([4, 6, 7])
print(type(a7))

# estas estructuras de NumPy se pueden transformar a listas o tuplas de python
lista_python = list(a7)
print(lista_python)
print(type(lista_python))

<class 'numpy.ndarray'>
[np.int64(4), np.int64(6), np.int64(7)]
<class 'list'>


Acá vemos en la práctica la regla de homogeneidad: si mezclamos enteros y decimales, NumPy **sube de tipo** todo a decimales (nunca al revés, porque eso significaría perder información).

In [ ]:
# los arrays de numpy tienen que ser homogeneos, por lo tanto todos los elementos deben ser
# del mismo tipo de dato
a8 = np.array([12, 3.14, 45, 7.6]) # ponemos tanto enteros como flotantes
print(a8)
# los enteros se han convertido a decimales
print(a8.dtype) # float64 --> 8 bytes
print(a8.itemsize) # vemos que cada elemento tiene justamente 8 bytes
print(a8.nbytes) # vemos el tamaño del array --> 32 bytes

[12.    3.14 45.    7.6 ]
float64
8
32


### Eligiendo el `dtype` a mano

Por defecto, si le damos números enteros, NumPy va a usar `int64` (en la mayoría de las máquinas de 64 bits). Pero podemos forzar otro tipo con el parámetro `dtype`, algo muy útil para **ahorrar memoria** cuando sabemos que los valores van a estar en un rango chico (por ejemplo, `int8` solo admite valores entre -128 y 127, pero ocupa 8 veces menos memoria que `int64`).

In [ ]:
# por defecto numpy crear arrays de int64 si introducimos numeros enteros
# podemos cambiar este tipo de dato con el parametro dtype
a11 = np.array([24, 56, 77, 85], dtype=np.int8)
print(a11)
print(a11.dtype) # el tipo de dato ahora es int8
print(a11.itemsize) # nos devuelve el valor 1, que es 1 byte ya que int8 son 8 bits
print(a11.nbytes) # el array tiene 4 elementos, por ende 4 * 1 = 4bytes

# ahora creamos uno con elementos de tipo float
a12 = np.array([24.34, 56.12, 77.1, 85.134], dtype=np.float32)
print(a12)
print(a12.dtype)
print(a12.itemsize)
print(a12.nbytes)

[24 56 77 85]
int8
1
4
[24.34  56.12  77.1   85.134]
float32
4
16
