<a href="https://colab.research.google.com/github/Gonza03s/intro-analisis-de-datos/blob/master/numpy_clase_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a NumPy: qué es y por qué usarlo

## ¿Qué es NumPy?

**NumPy** (de *Numerical Python*) es una librería de Python pensada para trabajar con
datos numéricos de forma rápida y eficiente. Es, ni más ni menos, la **base** sobre la
que está construido casi todo el ecosistema de ciencia de datos y machine learning en
Python: **Pandas** usa NumPy por debajo para representar sus columnas de datos,
**Scikit-learn** trabaja internamente con arrays de NumPy, y hasta librerías de deep
learning como **TensorFlow** o **PyTorch** tienen una API muy inspirada en la de NumPy
(sus tensores se manejan de forma muy parecida a un `ndarray`). Por eso comenzamos acá: entender bien NumPy es el cimiento para entender todo lo que viene después.

NumPy nació para resolver un problema concreto: **Python puro es lento para hacer
cuentas con muchos números**. Python es un lenguaje interpretado y sus listas son
estructuras genéricas (pueden guardar cualquier tipo de objeto mezclado), lo cual las
hace muy flexibles pero también muy ineficientes cuando lo que necesitamos es sumar,
multiplicar o filtrar millones de números. NumPy soluciona esto por debajo con código
escrito en **C** (un lenguaje mucho más cercano al hardware y mucho más rápido), y nos
expone esa velocidad a través de una API simple de usar desde Python.

### El objeto central: el `ndarray`

Todo en NumPy gira alrededor de un único objeto: el **`ndarray`** (*n-dimensional
array*, "array de n dimensiones"). No importa si estamos trabajando con una lista de
números, una tabla de dos dimensiones o una estructura más compleja de tres o más
dimensiones (como podría ser una imagen a color, que tiene alto, ancho y canales de
color) — todo se representa con el mismo tipo de objeto: `ndarray`.

### ¿Por qué no alcanza con listas de Python?

Cuando empezamos a programar en Python, aprendemos a guardar colecciones de números en
**listas** (`[1, 2, 3]`). Las listas son geniales para uso general, pero tienen dos
problemas grandes cuando el objetivo es hacer matemática con muchos datos:

1. **Rendimiento**: para sumar dos listas elemento a elemento, Python tiene que recorrer
   cada elemento con un bucle (`for` o comprensión de lista), y en cada paso hace un
   montón de trabajo extra por detrás (verificar tipos, gestionar memoria dispersa,
   etc.). NumPy, en cambio, ejecuta esa misma suma en código C compilado, sin ese
   overhead — vamos a **medir** esta diferencia en un ratito con un benchmark real.
2. **Memoria**: una lista de Python en realidad no guarda los números "pegados" en
   memoria, sino que guarda punteros a objetos Python dispersos (cada número entero de
   una lista de Python es, por dentro, un objeto bastante pesado). Un `ndarray`, en
   cambio, guarda sus datos en un bloque **contiguo** de memoria, todos del mismo tipo
   — mucho más compacto y mucho más rápido de recorrer.

En resumen: NumPy nos da arrays **más rápidos y más livianos**, a cambio de una única
restricción: todos los elementos de un mismo array tienen que ser del **mismo tipo de
dato**.

### Cómo se instala y cómo se importa

NumPy no viene incluido en Python por defecto — hay que instalarlo (en Colab ya viene
instalado, pero en una PC local se instala con `pip install numpy`). Una vez instalado,
la convención **universal** en toda la comunidad de Python es importarlo con el alias
`np`:

```python
import numpy as np
```

Vas a ver este `import numpy as np` al principio de prácticamente cualquier script,
notebook o proyecto que use NumPy — es tan estándar que directamente asumimos que todo
el mundo sabe que `np` significa NumPy.


##Importación y Creación de ndarrays


Un **ndarray** es la estructura de datos central de NumPy: una grilla de valores, todos del **mismo tipo de dato**, organizada en una o más dimensiones. A diferencia de una lista de Python (que puede mezclar tipos y que internamente guarda punteros a objetos dispersos en memoria), un `ndarray` guarda sus datos en un bloque **contiguo** de memoria y de un único tipo. Eso es justamente lo que le permite a NumPy ser mucho más rápido y mucho más liviano en memoria.

Antes de crear el primer array, conviene verificar qué versión de Python y de NumPy tenemos instaladas (esto es una buena práctica para cualquier proyecto: documentar el entorno con el que se trabajó).

In [ ]:
!python --version # version de python
import numpy as np
print(np.__version__) # version de numpy

Python 3.13.15
2.1.3


Ahora sí, el primer `ndarray`. Fijate que a un array de **una sola dimensión** (lo que en matemática llamamos **vector**) se lo puede crear a partir de una lista o de una tupla de Python — el resultado es el mismo.

En este bloque vamos a ver, además de la creación, los **atributos básicos** de un array:
- `type(a)`: el tipo de Python del objeto → siempre `numpy.ndarray`.
- `a.size`: cuántos elementos tiene en total.
- `a.dtype`: de qué tipo son los datos que contiene (`int64`, `float64`, etc).
- `a.itemsize`: cuántos bytes ocupa CADA elemento.
- `a.nbytes`: cuántos bytes ocupa el array COMPLETO.
- `a.ndim`: cuántas dimensiones tiene.

In [ ]:
# array de una unica dimension o VECTORES

a = np.array([3, 14, 15, 92]) # a = np.array((3, 14, 15, 92)) -> se pueden realizar con tuplas tambien

print(type(a)) # Vemos que el tipo de dato es numpy.ndarray
print(a.size) # Podemos ver el tamaño del array
print(a.dtype) # muestra el tipo de dato de los elementos almacenados en el array
print(a.itemsize) # muestra el tamaño en bytes de cada elemento del array
print(a.nbytes) # muestra el tamaño total en bytes del array
print(a.ndim) # muestra el número de dimensiones
a

<class 'numpy.ndarray'>
4
int64
8
32
1


array([ 3, 14, 15, 92])

Una diferencia visual importante: `print(a)` y simplemente evaluar `a` (como en la celda anterior) **no se ven igual**. El `repr` de Colab/Jupyter separa los elementos con comas, mientras que `print()` los muestra separados solo por espacios. Es un detalle chico pero que suele confundir.

### Arrays de más dimensiones

Un array de **dos dimensiones** es lo que en matemática llamamos **matriz**: tiene filas y columnas. Se construye pasando una lista de listas (cada lista interna es una fila).

In [ ]:
# array de dos dimensiones (matriz)
array_bidimensional = np.array([[1, 2, 3], [4, 5, 6]])
print(array_bidimensional)

[[1 2 3]
 [4 5 6]]


Y un array de **tres dimensiones** sería, por ejemplo, un conjunto de matrices apiladas (pensalo como un "cubo" de datos, o como varias fotos en escala de grises apiladas una detrás de la otra). Esto se construye con una lista de listas de listas.

In [ ]:
# array de tres dimensiones (matriz)
array_tridimensional = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array_tridimensional)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


##Análisis de Rendimiento Operativo: Listas de Python vs. Vectores de NumPy

Este benchmark mide la velocidad de procesamiento en CPU y la eficiencia en memoria al ejecutar operaciones matemáticas vectorizadas y filtrado masivo sobre millones de elementos, contrastando el bucle iterativo de la máquina virtual de Python con las ejecuciones compiladas en C de NumPy.

La idea del benchmark es simple:

1. Creamos dos colecciones de 10 millones de números, una vez como **listas de Python** y otra vez como **arrays de NumPy**.
2. Sumamos elemento a elemento en ambos casos.
3. Medimos el tiempo que tarda cada enfoque con el módulo `time`.

La clave está en la línea `resultado_array = array_a + array_b`: en NumPy, sumar dos arrays **no** recorre un bucle de Python elemento por elemento (como sí hace la comprensión de lista `[a + b for a, b in zip(...)]`). Esa suma se llama una **operación vectorizada**, y por debajo la ejecuta código compilado en C, sin el overhead del intérprete de Python. Por eso la diferencia de tiempos suele ser de decenas de veces (el resultado exacto depende de la máquina donde se ejecute).

In [ ]:
import numpy as np
import time

# Definir la cantidad de elementos (10 millones)
N = 10_000_000

print(f"Comparando rendimiento para un vector de {N:,} elementos...\n")

# --- LISTAS DE PYTHON ---
# Creación de datos
lista_a = list(range(N))
lista_b = list(range(N))

# Medición del tiempo para sumar elemento a elemento
inicio_python = time.time()
resultado_lista = [a + b for a, b in zip(lista_a, lista_b)]
tiempo_python = time.time() - inicio_python

print(f"Tiempo con Listas de Python: {tiempo_python:.4f} segundos")

# --- NDARRAYS DE NUMPY ---
# Creación de datos
array_a = np.arange(N)
array_b = np.arange(N)

# Medición del tiempo con vectorized operations
inicio_numpy = time.time()
resultado_array = array_a + array_b
tiempo_numpy = time.time() - inicio_numpy

print(f"Tiempo con NumPy ndarray:    {tiempo_numpy:.4f} segundos")

# --- COMPARACIÓN DE RESULTADOS ---
diferencia = tiempo_python / tiempo_numpy
print("-" * 50)
print(f"🚀 NumPy es aproximadamente {diferencia:.1f}x más rápido.")

Comparando rendimiento para un vector de 10,000,000 elementos...

Tiempo con Listas de Python: 0.9175 segundos
Tiempo con NumPy ndarray:    0.0272 segundos
--------------------------------------------------
🚀 NumPy es aproximadamente 33.7x más rápido.
