<a href="https://colab.research.google.com/github/Gonza03s/intro-analisis-de-datos/blob/master/numpy_clase_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creando arrays con funciones de NumPy

## Por qué usar funciones en vez de escribir el array a mano

En el video anterior creamos arrays escribiendo cada valor a mano
(`np.array([3, 14, 15, 92])`). Eso sirve para ejemplos chicos y para entender el
concepto, pero en la práctica **casi nadie hace esto** con datos reales: si necesitamos
un array de 10.000 posiciones, es imposible (y absurdo) tipear los 10.000 valores.

Para esto, NumPy trae un conjunto de **funciones "fábrica"** (*array creation
functions*), que generan arrays automáticamente según un patrón: todo ceros, todo
unos, una secuencia de números, valores sin inicializar, etc. Estas funciones se usan
constantemente para dos escenarios muy comunes:

1. **Inicializar una estructura vacía** que después se va a ir llenando con resultados
   calculados en un bucle o una simulación (por ejemplo, reservar un array de ceros del
   tamaño exacto que vamos a necesitar, antes de empezar a llenarlo).
2. **Generar secuencias numéricas** para, por ejemplo, los puntos de un eje en un
   gráfico, o para simular datos de prueba.

Todas estas funciones comparten una idea en común: en vez de decirle a NumPy **qué**
valores queremos uno por uno, le decimos **qué forma** (`shape`) tiene que tener el
resultado y **con qué criterio** llenarlo — y NumPy hace el trabajo pesado.


##zeros

`np.zeros()` crea un array **lleno de ceros**. Es muy común usarlo para "reservar" espacio antes de llenarlo con datos calculados en un bucle, o como punto de partida para acumular resultados. Por defecto, el tipo de dato es `float64` (los ceros se muestran como `0.`, con el punto decimal).

In [ ]:
import numpy as np

In [ ]:
#  crea un vector lleno de ceros, por defecto el tipo de dato es float
a = np.zeros(5)
print(a.dtype)
print(a)

float64
[0. 0. 0. 0. 0.]


El parámetro más importante de `zeros()` (y de casi todas las funciones de esta sección) es el **shape**: la forma del array que queremos, como una tupla `(filas, columnas)`. También podemos indicar explícitamente el `dtype` si no queremos que sea `float64` por defecto — por ejemplo `np.int8` para ahorrar memoria cuando sabemos que los valores van a ser chicos.

In [ ]:
# como parametro le podemos poner shape
# y tambien el tipo de dato
# Podemos obviar escribir shape y poner directamente la tupla
a1 = np.zeros(shape=(2, 7), dtype=np.int8) # np.zeros((2, 7), dtype=np.int8)
print(a1)
a1

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int8)

##ones

`np.ones()` es el equivalente pero llenando el array con **unos** en vez de ceros. Se usa mucho, por ejemplo, para construir máscaras iniciales o matrices de "peso neutro" en cálculos.

In [ ]:
#  crea un vector lleno de unos, por defecto el tipo de dato es float
a = np.ones(4)
print(a.dtype)
print(a)

float64
[1. 1. 1. 1.]


Igual que con `zeros()`, podemos combinar `shape` y `dtype` para controlar la forma y el tipo de dato del resultado.

In [ ]:
# como parametro le podemos poner shape
# y tambien el tipo de dato
a1 = np.ones(shape=(2, 5), dtype=np.int8)
print(a1)
a1

[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

##empty

`np.empty()` es distinta a las dos anteriores: crea un array **sin inicializar sus valores**. Es decir, NumPy reserva el espacio en memoria pero no se toma el trabajo de escribir ceros ni ningún valor en particular — lo que queda ahí es "basura", el contenido que hubiera en esa zona de memoria previamente. Por eso es la función MÁS rápida de las cuatro (`zeros`, `ones`, `empty`, `full`), pero también la más peligrosa si nos olvidamos de llenarla por completo antes de usarla.


In [ ]:
# la función empty crea una matriz cuyo contenido inicial es aleatorio y depende del estado de la memoria
e = np.empty((2,3))
print(e)

[[3.8e-322 3.8e-322 3.8e-322]
 [3.8e-322 3.8e-322 3.8e-322]]


##full

`np.full()` crea un array del `shape` indicado, pero llenándolo con un valor constante elegido por nosotros (en vez de forzosamente 0 o 1 como en los casos anteriores).

In [ ]:
f = np.full([2, 2], 55)
print(f)

[[55 55]
 [55 55]]


##arange y linspace

### `arange`: como el `range` de Python, pero devolviendo un array

`np.arange()` genera una secuencia de números, igual que el `range()` de Python de toda la vida, pero devolviendo directamente un `ndarray`. Admite los mismos tres parámetros: `start` (inicio, inclusive), `stop` (fin, exclusivo) y `step` (paso).

### `linspace`: espaciado lineal entre dos valores

`np.linspace()` también genera una secuencia de números, pero con una filosofía distinta a `arange`: en vez de indicarle el **paso** entre valores, le indicamos **cuántos valores** queremos que tenga el resultado, y NumPy calcula automáticamente el espaciado para que todos queden distribuidos de forma pareja entre el inicio y el fin (¡ambos extremos incluidos!). Si no le decimos cuántos valores queremos, por defecto genera 50.

Esto la hace ideal, por ejemplo, para generar los puntos del eje X cuando queremos graficar una función matemática con una cantidad exacta de puntos.

In [ ]:
# arange, similar a range de python
# aca lo vemos con sus diferentes posibilidades. start, stop, step
a9 = np.arange(9)
print(a9)
a9 = np.arange(4, 15)
print(a9)
a9 = np.arange(4, 15, 2)
print(a9)
a9 = np.arange(start=2, stop=20, step=3) # no tenemos porque escribir start, stop, step
print(a9)

print("-" * 40)

# linspace (espaciamiento lineal) es parecido a arange
# tiene un start, un stop y el numero de datos que queremos que tenga nuestro array
# se incluyen tanto el primero como el ultimo. Si no le decimos el numero
# de datos, crea por defecto 50.
# Ademas todos estan igualmente espaciados!!!
a10 = np.linspace(1, 4)
print(a10)
a10 = np.linspace(1, 4, 10) # le podemos pasar el tipo de dato, por ejemplo dtype=int
print(a10)

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ,
       20.71428571, 21.42857143, 22.14285714, 22.85714286, 23.57142857,
       24.28571429, 25.        , 25.71428571, 26.42857143, 27.14285714,
       27.85714286, 28.57142857, 29.28571429, 30.        , 30.71428571,
       31.42857143, 32.14285714, 32.85714286, 33.57142857, 34.28571429,
       35.        , 35.71428571, 36.42857143, 37.14285714, 37.85714286,
       38.57142857, 39.28571429, 40.        , 40.71428571, 41.42857143,
       42.14285714, 42.85714286, 43.57142857, 44.28571429, 45.        ])