<a href="https://colab.research.google.com/github/Gonza03s/intro-analisis-de-datos/blob/master/numpy_clase_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexación y slicing de vectores

## Indexación vs. slicing: la diferencia conceptual

Hasta ahora vimos cómo **crear** arrays. A partir de ahora empezamos a ver cómo
**acceder** a los datos que ya tenemos dentro de un array, que es algo que vamos a
necesitar todo el tiempo. Hay dos operaciones relacionadas pero distintas que conviene
separar bien desde el principio:

- **Indexación**: acceder a **un único elemento puntual**, indicando su posición (por
  ejemplo, "el elemento que está en la posición 2").
- **Slicing** (rebanado): acceder a **un sub-conjunto** de elementos, indicando un
  rango de posiciones (por ejemplo, "todo desde la posición 2 hasta la 5").

Ambas ideas ya existen en las listas de Python — NumPy las hereda con una sintaxis muy
similar, pero agrega herramientas extra (como el Fancy Indexing) que las listas de Python no tienen.


##Indexacion de vectores con corchetes

La indexación con corchetes en NumPy funciona **igual que en las listas de Python**: el primer elemento está en la posición `0`, y se puede usar índices negativos para contar desde el final (`-1` es el último elemento). La diferencia grande aparece cuando queremos **asignar** un valor: si el array es de un tipo entero y le asignamos un decimal, NumPy lo **trunca** automáticamente para respetar el `dtype` del array (no redondea, corta la parte decimal).

In [ ]:
import numpy as np

In [ ]:
# indexacion con notacion de corchetes
a = np.array([3, 14, 15, 92, 65])
print(a)
print(a[0])
print(a[-1])

a[2] = 777 # asignar en una posicion
print(a)

a[3] = 45.32 # numpy nos trunca el elemento y lo transforma en entero porque el array es un entero.
print(a)

[ 3 14 15 92 65]
3
65
[  3  14 777  92  65]
[  3  14 777  45  65]


Otra forma de acceder a un elemento puntual es con el método `.item(posicion)`. Es equivalente a los corchetes para leer un valor, aunque en la práctica vas a ver mucho más la notación con corchetes.

📌 **Nota histórica importante**: antes existía también `itemset()` para asignar valores con este mismo estilo, pero **fue eliminado en NumPy 2.0**. Si alguien ve tutoriales viejos que lo usan, hay que aclarar que ahora hay que usar la asignación con corchetes (`arr[indice] = valor`).

In [ ]:
# tambien con el metodo item()
a1 = np.array([11, 22, 33, 44, 55])
print(a1)
print(a1.item(1))
print(a1.item(-1))

# asignar un nuevo valor a una posicion con itemset()
# a1.itemset(2, 454)
# print(a1)
# AttributeError: `itemset` was removed from the ndarray class in NumPy 2.0. Use `arr[index] = value` instead.

[11 22 33 44 55]
22
55


##Slicing de vectores

El slicing ("rebanado") en NumPy también funciona igual que en Python: `array[inicio:fin]` devuelve un sub-array. Lo nuevo interesante acá es que **podemos asignar varios valores a la vez** usando slicing: si le asignamos un solo valor, NumPy lo repite en todas las posiciones seleccionadas (esto se llama **broadcasting**, y lo vamos a ver más adelante); si le asignamos una lista o tupla del mismo largo, asigna cada valor a su posición correspondiente.

📌 **Diferencia clave con Python puro**: en una lista de Python, si le asignás a un slice una tupla o lista de largo distinto al slice original, la lista cambia de tamaño (se "acomoda"). En NumPy **no** — el array tiene un tamaño fijo, así que la cantidad de valores que asignes tiene que coincidir exactamente con el tamaño del slice.

In [ ]:
# funciona igual que en Python
a2 = np.arange(10)
print(a2)

print(a2[:3])
print(a2[-5:])

# tambien podemos cambiar elementos mediante slicing
a2[-4:] = 777
print(a2)

a2[-4:] = 34, 45, 65, 23 # o como una lista o tupla se los puedo pasar
print(a2)

print("-" * 20)

# la lista de Python funciona diferente:
lista = [1,2,3,4,5,6,7]
lista[-4:] = (65,)
print(lista)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 0  3  6  9 12 15 18 21 24 27]


##Indexacion de arrays con listas


#####Fancy index
El Fancy Indexing (o indexación avanzada) en NumPy es la capacidad de acceder o modificar múltiples elementos de un array utilizando listas o arrays de índices en lugar de escalares simples o cortes (slices como 0:5).

A diferencia del slicing tradicional, que solo te permite extraer bloques continuos o con un paso constante, el Fancy Indexing te da la libertad de seleccionar cualquier combinación de elementos en cualquier orden.


#####https://www.programiz.com/python-programming/numpy/fancy-indexing

La diferencia clave con el slicing tradicional es que el slicing solo te permite tomar **bloques continuos** (o con un paso fijo, como `[::2]`), mientras que el Fancy Indexing te deja elegir **cualquier combinación de posiciones**, en **cualquier orden**, repitiendo índices si querés. Esto lo hace ideal para, por ejemplo, reordenar filas de un dataset o seleccionar un subconjunto arbitrario de registros.

In [ ]:
a3 = np.arange(1, 15)
print(a3)
print(a3[[0, -1]]) # mostrar primer y ultimo elemento

print(a3[[0, 3, 6, -1]]) # con una lista puedo buscar los elementos que quiero

a3[[0, -1]] = [77, 88] # cambiamos el primer y ultimo elemento
print(a3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  5  9 11 14]
[77  2  3  4  5  6  7  8  9 10 11 12 13 88]


Un ejemplo práctico y muy típico: crear un array de ceros y encender (poner en 1) solo algunas posiciones puntuales, no consecutivas. Con Fancy Indexing esto se resuelve en una sola línea, pasando la lista de posiciones que queremos modificar.

In [ ]:
# crear un array con 30 ceros, pero que en tres posiciones no consecutivas tenga un 1
a4 = np.zeros(30)
print(a4)

print("-" * 40)

a4[[3, 14, 23]] = 1
print(a4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
----------------------------------------
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0.]


NumPy también ofrece dos **métodos** que hacen básicamente lo mismo que el Fancy Indexing pero con una sintaxis de método en vez de corchetes:
- `.take([indices])`: para **leer** varios elementos por posición (equivalente a `array[[indices]]`).
- `.put([indices], [valores])`: para **escribir/reemplazar** varios elementos por posición.

No hay una ventaja funcional muy grande sobre el Fancy Indexing con corchetes, pero vale la pena conocerlos porque aparecen en código de otras personas.

In [ ]:
# indexacion de arrays con metodos
a5 = np.array([10,11,12,13,14,15,16,17,18,19,20])
print(a5.take([2, 4, 7])) # utilizando el metodo take

print(a5.take([0, -1])) # utilizando el metodo take mostramos el primer y ultimo elemento


# cambiar elementos con put()
a5.put([0, -1], [444, 555])

print(a5)

[10 11 12 13 14 15 16 17 18 19 20]
[11 14 18]
[10 20]
[ 444   11   12 7777   14   15   16   17   18   19  555]
